sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"

branches:
  only:
    - master

install:
  - make dev-setup

script:
  - make test

matrix:
  allow_failures:
    - python: "3.6"
    - python: "3.6-dev"
