sudo: false
language: python
python:
  - "3.4"
  - "3.5"

before_install:
  - pip install pycodestyle

install:
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - make test