sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
env:
  matrix:
    - DB=postgres

matrix:
  include:
    - python: 3.4
      env: DB=sqlite
  allow_failures:
    - python: "3.6"
    - python: "3.6-dev"

branches:
  only:
    - master

install:
  - make travis-setup

before_script:
  - if [[ "$DB" == "postgres" ]]; then psql -c 'create database nextcloudappstore;' -U postgres; fi
  - if [[ "$DB" == "postgres" ]]; then echo "DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'" >> nextcloudappstore/settings/development.py; fi
  - if [[ "$DB" == "postgres" ]]; then echo "DATABASES['default']['NAME'] = 'nextcloudappstore'" >> nextcloudappstore/settings/development.py; fi
  - if [[ "$DB" == "postgres" ]]; then echo "DATABASES['default']['USER'] = 'postgres'" >> nextcloudappstore/settings/development.py; fi
  - if [[ "$DB" == "postgres" ]]; then echo "DATABASES['default']['PASSWORD'] = ''" >> nextcloudappstore/settings/development.py; fi
  - if [[ "$DB" == "postgres" ]]; then echo "DATABASES['default']['PORT'] = '5432'" >> nextcloudappstore/settings/development.py; fi
  - if [[ "$DB" == "postgres" ]]; then echo "DATABASES['default']['HOST'] = '127.0.0.1'" >> nextcloudappstore/settings/development.py; fi
  - cat nextcloudappstore/settings/development.py

script:
  - make test


services:
  - postgresql
